### ISSUE TITLE
[Android devices] It is not possible to scroll through the homepage scroller posts.

### ISSUE THREAD

**Issue by benvoide** [nicoandrade/Tography-Lite#1]
If you access to a expanded post from the scroller in the homepage, it is not possible to scroll down the page.
Evidence:
http://www.2vphoto.com/la-tua-strada/
![](https://cloud.githubusercontent.com/assets/2467829/20695572/d33518b6-b5cb-11e6-9da2-5d039e1310e6.gif)

**Comment by nicoandrade** [comment]
Fixed on 1.0.13
